spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:/Users/yuyijun/Desktop/work/private/vw-hub-server/vwhub.db


vw:
  hub:
    input:
      dir: /Users/yuyijun/Desktop/work/private/vw-hub-server/input/
    output:
      dir: /Users/yuyijun/Desktop/work/private/vw-hub-server/output/
    map:
      json: /Users/yuyijun/Desktop/work/private/vw-hub-server/src/main/resources/static/map.json
    py:
      dir: /Users/yuyijun/Desktop/work/private/vw-hub-server/alg/location-master/
logging:
  level:
    com:
      fish:
        vwhub:
          mapper: debug