spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:/Users/yuyijun/Desktop/work/private/vw-hub-server/vwhub.db


vw:
  hub:
    input:
      dir: /Users/yuyijun/Desktop/work/private/vw-hub-server/input/
    output:
      dir: /Users/caiwenlin/java/vw-hub-server/output/

logging:
  level:
    com:
      fish:
        vwhub:
          mapper: debug